model_type: TripletModel
manual_seed: 100
scale: 1
num_gpu: 1

datasets:
  root: /data/storage/datasets/Lowlight-datasets/OURdataset_linear/nikon/
  train:
    name: TrainSet
    type: Triplet
    data_gt: train/high
    data_lq: train/low
    geometric_augs: true
    
    filename_tmpl: '{}'
    io_backend:
      type: disk
    
    use_shuffle: true
    batch_size_per_gpu: 16
    num_worker_per_gpu: 4
    
    total_epochs: 1000
    gt_size: 128
    gt_sizes: [128]

    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true
    
    return_I: true
    return_chroma: true
    feed_I: true
    pred_I: true
    pred_chroma: true
    Ifrom: sensors

    gamma_in: 1
    gamma_train: 1
    gamma_out: 1

    i2use: all
    color_input: ["White", "Red", "Green", "Blue"]

  val:
    name: ValSet
    type: Dataset_PairedImage_Custom
    data_gt: val/high
    data_lq: val/low
    io_backend:
      type: disk

    batch_size_per_gpu: 1
    num_worker_per_gpu: 0
    return_I: true
    return_chroma: true
    Ifrom: sensors

    gamma_in: 1
    gamma_train: 1
    gamma_out: 1

    i2use: all
    color_input: ["White", "Red", "Green", "Blue"]

  test:
    name: TestSet
    type: Dataset_PairedImage_Custom
    data_gt: test/high
    data_lq: test/low
    io_backend:
      type: disk

    batch_size_per_gpu: 1
    num_worker_per_gpu: 0
    return_I: true
    return_chroma: true
    Ifrom: sensors

    gamma_in: 1
    gamma_train: 1
    gamma_out: 1

    i2use: all
    color_input: ["White", "Red", "Green", "Blue"]

network_g:
  type: RetinexFormerEmb
  in_channels: 3
  out_channels: 3
  n_feat: 40
  stage: 1
  num_blocks: [1,2,2]
  use_prior: true

path:
  pretrain_network_g: /home/priubrogent/00_PROJECTS/03_TFM/paper_code/runs/POL_znikon_linear_600x400_baselines_colors/Nikon_all_linear/best_psnr.pth
  strict_load_g: true
  resume_state: null

train:
  total_iter: 150000
  warmup_iter: -1
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   

  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    betas: [0.9, 0.999]

  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

  losses:
    l_sd: 0
    l_m: 1
    l_tr: 1
    l_chroma: 1

val:
  window_size: 4
  val_freq: 1
  save_img: true
  save_img_freq: 100
  log_img_freq: 500
  rgb2bgr: true
  use_image: false
  max_minibatch: 1
  
  metrics:
    psnr:
      crop_border: 0
      test_y_channel: false
      type: calculate_psnr

test:
  window_size: 4
  val_freq: 1
  save_img: true
  rgb2bgr: true
  use_image: false
  max_minibatch: 1
  

logger:
  print_freq: 30
  save_checkpoint_freq: 1000.0
  use_tb_logger: false

dist_params:
  backend: nccl
  port: 29500
  
launcher: none
gpu_id: [0]

wandb:
  project: CHROMA-MILL-Retinexformer
  entity: tfm-priubrogent
  resume: ~              
  id: ~


